# This manifest creates the keycloak-oidc secret for GitLab OIDC authentication
# The secret data should be created manually or via sealed-secrets
# kubectl create secret generic -n gitlab keycloak-oidc --from-file=provider=provider.yaml
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-oidc
stringData:
    provider: ENC[AES256_GCM,data:PzUhrCgWHkqDZVexUQfBgdyd3dMJo0P863EPnaR8/UVS2b46nAJ2sQc0304WfydmDNQ46Vi8GPuv0mFm+n1fcRPLMRzHt+NbToRLSYcUjzOllTOKxXXJSsRqHH839TJA1nK8NphNvo/VKmfOzRaxT+OXdxkN8/66HhGUogbEnFREIFh5Oq9QyZMntR9NS8yBgyzdaDVWsApzL0xaBKSgcLq+9CIa0/LryUaj2FsYZGr3GBNk6vUCaSfV9rKOcBT/U38ZTHbncaKeGTyGYzGs6DV2ivLv8h+pcSyCSSjWOeN8ZyMGl3RYBXJwVUWsYMPlaGlNGgGu7CDl+0CEC7MGk9eA9mA/zGY89538oh10bK42RNOV4IotObC3yLURi7tlRHdYMRfJW9ub4JUHr6cEC4pWsnmwOL7TPDwijKHzdh3zeHB59qicEV3UoxJO+zCEonUwFEEkYpRqDqgPPA/5Cd9a+YwhPHkwiVKBhOiKpRszKQAIf76n1/+JI5DefnIsFIG0nKcU9YUtPuY2xUMC1xZzSKyFRZXkkRvmJScKtCo2v8xGsQIGPS3gK69t5MegvBiwUuUXeMgYHw90/w8euyF1y/xdarvSpPu8MenlRfmu3KB1AOow3eCGVzckoNtoY49j3ILAY1I=,iv:T4nxHqY3rqm9L+orL/rcRvbMvUdg/YKbemdpWxLpi/I=,tag:Nu/m6q6uYfyOLx5hM3r7Bw==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVzdGb1QxNjEwZURrNXlI
            NnZQSStNai83Z2Q5cjBLb1BnMnhTUFFZMm5jCmR3dFJvY1Qwak1md2s5bHZLMzFt
            dUQ1VTJrSGJUTUF4MTBMWUx6ZnlDWkEKLS0tIGxzNk5XbGZwVFRrVE1yREtiZEtH
            SkdpWDBqdWtUL21tU2RYTXB3alhELzAKsG42oe+JkKSPFnCG9koRgwIk2tFwjxgL
            pKO2zL2afpZ6+NMvSS6+JOyDcRtjUal9/sJz7WkSQ+F3NNdYQWKdiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:33:57Z"
    mac: ENC[AES256_GCM,data:GfHHkVorIaTJWYs/IJ3QoTUNq88nES0OM6Cm0g+9YBwRKToanCsVt6NXH0tBtV5VodNWN1NXuW4kR2cwmjtXA3cWdw3Hah0kC/xQ0HRqnUx5apZdVIuOO731TLGZQz1sDRqDpBTiK/Ve4PjM+R1Vp1MQ9Wgtqn1VXBDJUREzMso=,iv:82K+zoGzm9WX2rSEqQ2K/B8SD0SCfk4bMfDAl9r+vKY=,tag:Mejf0NhZwxOZvoTrQSkQlg==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
