---
# Keep kustomization namespace empty so resources preserve ${NS} placeholders
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gitlab-rails-secret.yaml
patches:
  - path: gitlab-oidc-secret-patch.yaml
    target:
      kind: Secret
      name: keycloak-oidc
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: gitlab-ingress
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/postBuild/substitute/HOST
        value: gitlab.winfra.cs.nycu.edu.tw
      - op: replace
        path: /spec/path
        value: ./manifests/ingress/overlays/winfra-prod