postgresql:
    postgresqlPassword: ENC[AES256_GCM,data:xmmp2Wq7VL7zI1zu,iv:qCBTBb2AwJ43+swR28RhKTb0dpyrh5+qTamTpX0I8MQ=,tag:tuh+wlQPLsd6jI+fEsNG5A==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSzRhR2RWM2x0cFNQelc1
            RklsWllJb08vaVJESlFaeTRwT2VEa1ZlckR3CnFHNUVyL21RdXpaZUQ2NVQwSVlQ
            TXcrdjhFVWVYd2k4cEtWMUtWdEd5d1kKLS0tIDdhemtBbkZVWnpNcFVvMWkyOHRN
            ZmpTMEwzZUE1eHhRcnhRNnBoWVFMcTAKDQhIxgO7TNvVnGaA5NR6DgpxMbHpzcJA
            au4wLI5+ol0zEvw9kwF0gNEIB1ODEKIpA9qD59kUMpOvhiJvtrtzKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:24Z"
    mac: ENC[AES256_GCM,data:gQMuvUMsbIeKuKXSTE1APSNt/N5IqtzdqJVZ3i0eQInWSLqVBNQrXjYmMWuZu9lpiXgDsttXUujtuULw08YlCqJH68UMmqi6G5fMhg3mVDBsvoo+omZXul1uvwkhG8pP6lIZKPACmTR/3M+0X7UppnjqENjDJiGxxFHiiScN1R0=,iv:5sk4WUsXwoSdMGDuyET6Eja+peWl3VBqjE0yVP9EbTE=,tag:GjqxdT37JF7fHHef48olyQ==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
