auth:
    rootPassword: ENC[AES256_GCM,data:L0LzkpxL1y84ThfH,iv:6OU63x8etLa6knluERxsy+2J4Bd0p0xXR2DsS6aHUQw=,tag:mEYhpNvIBj3uxses7l06MQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxKy8zRUd5eG1wRWpYRGdt
            b3k0aGF5a0FCRVBBMzdjWWc0Y3hYckI3K2t3CkFjRElmU2lra1VLQXQybkloaFd1
            L25ESGMyT2R2MnF2MTFkSVNIa1M5dlUKLS0tIEJiVTlZZkJaUjZ5Tk84MFFsZmxm
            K2RISHJKZXRxQ1dXeGxaVVg2VHFTVXMKo6B1g+NYONKqY0VcjLXz+q7XYoUxcpCH
            bP4fzRe+IbjsP+V+K6IFMMjLRsbksS6X9xKD9nOpefjgI5+aekRtZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:21Z"
    mac: ENC[AES256_GCM,data:PndA/zD8+FM1KlVtAKgiHXGQw4tiVRK9sLcvTAIXp8SXfRDYTyDpybPcE4sAFPLIG3xK/oTCBsVFDjxbPEQKp7gAHDB9JXUxGiDEm35csQJj0AQLryOmJArvQZWgwwsnN230MpY9yAcFMUaBU68qhpAizJjA4JI1ENECc0x2qLg=,iv:VUG2Ayj4HytXprULMBZSlUJWOdRg2yhI3u6ozh/JmQo=,tag:0vZ0R2YoRuuejt1equeZQQ==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
