nextcloud:
    password: ENC[AES256_GCM,data:vGUJoj7aQqtNNto6,iv:yp/Aeb2veJg/3Mfw+lg+NOoDwdTF256Z0dw+QBebWik=,tag:DEUzpXy/G4wgVU7Dm+RtBA==,type:str]
mariadb:
    auth:
        password: ENC[AES256_GCM,data:df6JMyLgWfP5YNyk,iv:4OVdD9QqljZYa+jcjE/D1QX0raFuqAzwimoxv8st+Gc=,tag:fXJmLSY7u7Fi/kNU5cmP2A==,type:str]
        rootPassword: ENC[AES256_GCM,data:UJyvCp7YIX45N1FJ,iv:fZAniOPp9p2wvfH0YPQRx032TSo9eqUysyLWkG/S+/0=,tag:+ywXv0EWupJm0mWv4gcf5A==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNWFxUHhQU1I2N3RnR0gr
            VzNSaU5UUGNZVmVhNnBpR29HcjltOHpkTjJFCk5ZYmhVMlcyQmlhODdVWDdFQWRD
            WXNJR1B6RzllVmROTnBvM2N4OUhHR1EKLS0tIEJEZnFacHNSK0lua1NYQWt6djBT
            MXhOUTRMN05WR2ZJcVhsUnM3Qjd5SGsKB4veh0i3v9zukQzSa+SE98jG5mNLhDMR
            5n0B8OKArZTjJ2zGl0W01h/Z/58LDyjO75zL89AO3DHetbwoUoPZBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:22Z"
    mac: ENC[AES256_GCM,data:rDhNM8/Nknyvz6vjWUll19X77sHqEr5x3Xjp/bNW8Q3DTKaZH1nWRceMVLTFZs6QHeqhuJZ7ojloARhRiDKk27PmFJ1KksjGBhB1BvN7WWlvMXUg++6Tgnoil8rIEjjnUIcHB/+PvqgUTRPnyRXnm4XXhW7SaAqidI8KJm3Q6W0=,iv:NoHtrX/goLlQNsJXhWHU1pS0iUx+LXOfsowEr8zxGNc=,tag:rdlfY2+O1Fngfe3WPWQOqw==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
