apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-ingress
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/ingress/overlays/<cluster-name>
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  postBuild:
    substitute:
      APP_NAME: harbor
      NS: harbor
      HOST: harbor.example.com
      SVC: harbor
      PORT: '80'
  dependsOn:
    - name: traefik-manifests
    - name: cert-manager-manifests
    - name: harbor-app
