loki:
    storage:
        s3:
            accessKeyId: ENC[AES256_GCM,data:NKjOzHToIvCNfRP8FIjX+jcvMg8=,iv:VakJnnaNXilS5yuZ7vIN1a9Oxk0Skm785qGTnjdsMTM=,tag:Pt9NMEVojIyI/tq38Ww2sw==,type:str]
            secretAccessKey: ENC[AES256_GCM,data:WOB21TvDuJSc6652l0EhjKGuPPc3fIwNotx9+S+WqdiAJ8RhpsLepA==,iv:dmYlXqbekkYIZZ4PNKYd04W8JSmbhtq/12ZB4DUinQk=,tag:s3IyjHmjVA32iWGvm/gJNg==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHJsVmJPWFczQ2VkTnpv
            QzJMZGRFVWg2VDM5bHp2L05Hd3I4bmIybGg0CnQyaUVhemZ0MGlXS2Fnd1pkUmVC
            cFB0WFJ6SUFSRkE3QjlKaXZ0VTd1SDgKLS0tIFNtdFVkNnlJQVB4b3dSd1BZYUp0
            MmxKV1lxYnkxWGZ4c3BPMGM4all5MkkKHEf4ltZz285luJQPmb8P6YaLJzMyiVaJ
            DpthRb7V3AQh2t/y5frs3utZ+9s2FDG5XkiphAa41nmRF4lHj3hTXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:31Z"
    mac: ENC[AES256_GCM,data:XYG3jU0Y8keUdqVu/Ryk0uJRgxV8DfeYw9xN6HU5CdPESWLWrGD0L8W+gDSzai3yGdB0PySa29CIsk/n0xEBnLeHRUQ1WaochO6aJS/V2Z8M9URgECYog5lwQOwsarTW1Ix2y77rdv7UyO97SKp1jqjjLx6cpUMzuHOXE0/Q+o0=,iv:o59+jcgfehGw+SSYtcByRi8ckjcVmNkKRm4XT47C/oo=,tag:jhBu25lirECiANV0gWaVmg==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
