mimir:
    structuredConfig:
        blocks_storage:
            s3:
                access_key_id: ENC[AES256_GCM,data:9LgDigD8khDsEyQv+6/NCmSnadI=,iv:iZZydTEU0rlzSAcd6ETwfGCWbOv9kUqfer+kd6GPW50=,tag:FTv0kTq3sAl02X81hKnu2g==,type:str]
                secret_access_key: ENC[AES256_GCM,data:fRCZCKcTcdaVx0woBiE3NViMhkW5gNbn15zRSWbEM7UF56vXNwlwhQ==,iv:uZvI5ikvQZxY1Bkvt9XfWtV7kXPaBTZVwO7u+q1F4DE=,tag:IN6uIxdEtXX/8dXRhF9SXA==,type:str]
        ruler_storage:
            s3:
                access_key_id: ENC[AES256_GCM,data:Djp+nymRoUGRTosJVrKso65DS7A=,iv:tXlEZyddwEsIVWBMlJW0MDF6jgQ4uw93CjpFKR4HABg=,tag:mNwuz3wULqVl+XUHwwz9zA==,type:str]
                secret_access_key: ENC[AES256_GCM,data:Zpu0M44TinTI2LrFOttfLFw/UEhtb3BgL67EMe5DMwVqJ1KN2f8NvA==,iv:XjPANRm4S2idjTdTfLfIxDSpIteJUcoDCqrI7HKtdmU=,tag:y1xl3W9UvKrLgGfKawjWqA==,type:str]
        alertmanager_storage:
            s3:
                access_key_id: ENC[AES256_GCM,data:8qUyO3uBQXPHPmoFHJWPfsIbsz4=,iv:6kElHm/ubWpru6PVlteTGrjQ1kPwLErIUOONQo7Wi2g=,tag:uqQfcGOitME0A1PTmQhJyA==,type:str]
                secret_access_key: ENC[AES256_GCM,data:zuPTz7cxFJQggv/kQSMgt+XO2Oh1RWAZn0aK8ZaarOr85jFbsIcDKw==,iv:t1kj52swJ8w2FNvPmS8wvAvgOrBQKGuDwxWRKPeqSaQ=,tag:tLs9pKMlVBfmdF0mLPKFIg==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSXUzSnFyRUlmTU83cDlE
            TTdQaTd5NmVnMGxGNjd4RlFKSXNGK3hJbGxvCjhXUjJISzJlc3QxbXU4YytaV2ZB
            a0NxTm9xZmR6Z05NUGRBVDhDVGF4N2MKLS0tIEVMZDZqNGtPbU9QcUxoQys2L1B1
            dGQvSlJQczZnTVdGSTFpS3FwN3puNVUKvksBvq9VJf2ayzX+UxAFCHPc7UDcbPCZ
            bNY9EyMcKdTiJTh33xamEH900Vcjvy3AXHF43ePZq7xJwVc1lwYDjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:28Z"
    mac: ENC[AES256_GCM,data:prhyp4llcbDJwSPRwSluKFGD1CAsQGF8ztfT8gGBWryfPQPDWhgavR7q8bwGBnbqHpKipNIc/mmwdmMsMBBeIzuztATXKhmNy6eZifhjCYHgBo1+Vpj5T4g4y81y+V7iMYB04GHL2ddwcblzG/OT2PWD2ADydH591fkPh2fwF/w=,iv:bK9j0OW3llsbolSXoGEkBiOBtj+4fosbwZanw0ozCHs=,tag:taX7qlAFVoqTKiqIQf0aJg==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
