harborAdminPassword: ENC[AES256_GCM,data:dQpjsnv5C6u0GFDh,iv:5CNlkPuAK7z5AypcIegUjgy5FyaQlG0hoEvLl9SmUqs=,tag:COIclLcNm030VeIIpg9Dmw==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdFdJb1Q3RVBTYkN0WFBa
            Y0NMM1hxMVliS2JSOERSQjZPV2RkZjZWdVRvClJnRjlnR0JXRmFQTzZtdFRUMUtB
            ZmwxdFdkNW1NZk9vMEpNanVVSFRuUGcKLS0tIGN3S1BhTVpTVGtTVTZBTGFrMnAw
            NTlkRnBoNHpvelQ3Y2l1ZGQ0Y0M2WDgKr48jJcnskNNb8DEXYYUIerXiXCb7ZK5t
            8hn+XhH6XelK/rEZ3JfkC7NvM4uZ4yOrj/JJCUufLJZjHPPgoaqOcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:06Z"
    mac: ENC[AES256_GCM,data:/tfatjvRoC1kyP5WG9O8ot0+ii+19mq5wONWDKT8lSiIbBGuWlwPAAgZaxbYzVEgSQCW8tUaswiQlYxW2Y5Klkovwirxlrbz3OOKyhwiRytfMnbQj7oM6fykZJUeOy7gdQNGrDCytZP5nMmoDA76KTlIhBqJXfsTr+ypduU6a/o=,iv:K12kcrJbdRu/LfSRbE2bzx5NGIvbtueDr5gAnoxe6uI=,tag:o6C/LFEO5no2s55QlMoqMA==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
