adminPassword: ENC[AES256_GCM,data:jS3wW5HTNlKizBAQ,iv:U9bQykStq4taH3QTwrWpnGHKiVZRLVYKUxV/WYnTgtg=,tag:eCpZT2Wp08qx7yrzkaskmQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYnVSWG1CNlNtV3RLSjJE
            SEJucVl4eXpueXhjZ2JsNm1WQVhLMTdXRDJzCkFXUzRkSGVGdE5uK1VWQ05CUFVk
            SFd3cTliYXk4bVVTaVdwRTZ2NVhta0kKLS0tIG9Ya0hHcTNrTjF0RXQzQXJITG5E
            NzRvaXZxWW96M25ORDNJQUR3NU42a3cKr1M1n0fpQ/NIa9MQpwmsMFBDz++6oMjL
            rxcrftFkqb436QDHmvIIiSvqbFijMT7Gro+wRq/E1klo9/pF3uoDRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:23:58Z"
    mac: ENC[AES256_GCM,data:uSj4osC+pa7xEsM0EzQILkKp6VNR1fcza2ivsayDGIvPlxCuKd9O1KHad8ceKrxq7l6EabFyHBs8AcCGTSfiSQx3ezHr8jge/3CYQ/CQ0TulapsSzf4XRcHBG0a81T+flknqxmSIyvDYWreNXcUon9kNKiiGvbaqEcWLBhRTru4=,iv:NvVBNxXq3TAGDBKS7vySDlcPjEoA7i4tx3750I2lics=,tag:U1nM5ztD+WRHbmpiePH9rA==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
