tempo:
    structuredConfig:
        storage:
            trace:
                s3:
                    access_key: ENC[AES256_GCM,data:81VpwLRAaiMoaXLj7hghFCBKLD0=,iv:rmrAQKZE5vrdZV9O9floraDXwIuRIkN8ib5KoDzVXe4=,tag:RCzw5sbciJhnLJvWHEyF2w==,type:str]
                    secret_key: ENC[AES256_GCM,data:X5orwFr6mJB/o7ASRCdCWHRPzgw3lxq/X18PuC2JbQG0w7YYiOagkA==,iv:7CDPNh902N7qySWAMClJO9jQCw7eaKon3YCPUcyLPrI=,tag:qA+gFuJV7R3jKZrDyFBCDQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTk1GRWJZVlR2S215TUtS
            R2NySXlRVUp2OFFYRXI0QWUwNzhXWmRJVDFzCkNoMTIzV0x2N0NTWlVVVXlYSm5t
            dmhLLzU0b2pMRm5MWUhKSm9XV2JZaVEKLS0tIHlBRjkwTjhBNHVrNnhhSUNSRjMr
            eWZ0QlozNVZZaXJPRUxWNDB6ZGpKaUkKCJALNgG2SXcSn0Pe99Gha0OMkYtaLNH1
            0325O0vZDP9aU5spuS4pZdcdxrVnsOGBwaIwHSZ0M3noF5O/VIuUkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:30Z"
    mac: ENC[AES256_GCM,data:PZTx+Gir9Exw7CJMOqih4UcR/kblijW+WXcWaNLJXZIkz4NJ6mTuwOlKYX2CyqmEdDEmqD8cEZBUv+kAOkSSo0IvQEBzCFehFksBmqNpbKI6OFFNYa0dsBwjxLfnv/Ju03/CYE0GPcV3wxygTHjbKeujto1CMsqTrzKhlUTwVRo=,iv:ZDaQ3nUtaGhQvHcXuqI4vnbNDPJsxBD61jxh9clTDC4=,tag:PCRA0WfSiXz8iPUiS8rA+A==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
