credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:PSUzI3MkWBu1Y+vnqSQBV2iijAoAXrGwwtjawZwKSEfgv6xGb78v7hnkpi1KVo0zhj0DXJLI+zSJIMQiDMWSfZCVrvOwcu0sqFrx1/tMo9thmI3j3gXqP2eAustVKWPlSAd3PuuK3XFIrFZNORNuqD7vvRQ=,iv:9MUyyOAXzlUD3zSphDSaCbduEU+N9hxQm9BoSwW3qjQ=,tag:8j0XmgbDSM5mybDig7x1Yw==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOEUyYitPS3dLTG5nNDN6
            WGY2SGcrTnpFUmszU1E1QXpjUWpEYmMvVFVFCmFzQUZUU3AvcEZxMzVZMjBTTEwx
            UExKOXdCSlpYV0pFeVpIV1lEU0JxTVUKLS0tIFNCVk1FYzhCRnZFRlZkd0svRVVZ
            UVJKcE1vYXA1OElGVkYrSm1raStFWWMKV1JLRHL5prTzPXLqZULnN+FphrOrBOJE
            7AyeNzPnHF5C7T0mdeA1vZ3ATo8fSjOitvKtzo76eGGxh0pfLyknyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:37:28Z"
    mac: ENC[AES256_GCM,data:9sVYWQz82icFE5lFxg1xpWKQvhVKi29gs9Qui2yTaS2GaOTRMNQli/SnCnxV9Na1R81D5jciOSbj9iJCWeYkAyiD1VXCC22Jzp4ljSzE8Xj3zY8MKWG8RMtSfPrArIMA4F1LC6j/uxQ1xsTXhF8X9w9RNmFRRmIjzvHghbePxKo=,iv:pGbxXiayWqlc1BvMpyvbzwMl4T1a2poY7sRm+/kgH7o=,tag:jt9S2xhcdySpV1umk5aJSg==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
