auth:
    adminPassword: ENC[AES256_GCM,data:USMjDR2XWgmRp5aJ,iv:WJ3fei2wf3XrfBGnXEGrpAlCbiA9tdUz+CRdaVgMelQ=,tag:FsAXOPz0P2+T531z+eQRhQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNGhLdE9IY29SUTBoR1JU
            cU1yUkJ3MWtNSTdHYVlLYUpRRzl1ZSswNkZBCng0U0ZQakRVYytzQUpIbjBPQmNy
            RkZQamVHdERvQ2Z0RzVZVUNqTmhNQ00KLS0tIDAwS2IvbnE4N01wNHlHZGlMclZG
            Ti9yamNrNEdOZ0hCSTdQa2JLQllOT1UK6qsOvU6LgD38COnRljlRXsQ+l0OTaaEr
            fF/baPmENNG5LZI/CN5+zEQ05VlTF+pWAY7eGpQBAUvgYzFk9nuOmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:15Z"
    mac: ENC[AES256_GCM,data:Fo9oedmGN48XorxkpgvfqTXrs0aKxLYgsicFkoKZupRLH9VCPArtLrvvn3teeBvUzh+HXMRVAgjkL2Z1sS0iWu/nHWsxPBFUCx09/3jSpZTtjfR6lHcQksiXVom8CON7UQ2tmUGdcsZVdtvs94wKZbbrbSb+owVEVKbHLCBYUoI=,iv:sY0Rti+lfk5mEp89dA5Nydrs/wHC+VU3FykJqZomHtA=,tag:SFDby8jd9P7fRfLosQ34iw==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
