---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/cert-manager/overlays/winfra-test
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  dependsOn:
    - name: cert-manager-app
