---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cert-manager.yaml
  - traefik.yaml
  - velero.yaml
  - kube-prometheus-stack.yaml
  # - loki-stack.yaml
