---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/loki-stack/overlays/winfra-test
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  dependsOn:
    - name: loki-stack-app
