---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner
generatorOptions:
  disableNameSuffixHash: false
resources:
  - helmrelease.yaml
  - namespace.yaml
configMapGenerator:
  - name: helm-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
