---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: observability
spec:
  interval: 10m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: prometheus
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-helm-values
      valuesKey: values-prometheus.yaml
    - kind: ConfigMap
      name: prometheus-helm-values-override
      valuesKey: values-prometheus.yaml
      optional: true
    - kind: Secret
      name: prometheus-helm-sensitive-values
      valuesKey: values-prometheus.secrets.yaml
      optional: true