---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - keycloak.yaml
  - minio.yaml
  - nextcloud.yaml
  - harbor.yaml
  - wiki.yaml
  - gitlab.yaml
