---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - ../../base
# patches:
#   - path: patch.yaml
#     target:
#       kind: kind-to-be-changed
#       name: name-to-be-changed
