---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calico-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/calico/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
