---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/kube-prometheus-stack/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  dependsOn:
    - name: kube-prometheus-stack-app
