---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/observability/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  dependsOn:
    - name: observability-app
