grafana:
    adminPassword: ENC[AES256_GCM,data:0pgM7RJjJC//VbjY,iv:HyAES3i/EeOfVAshQpaIXB3WCiRg+TlxYq+A/7QIfnU=,tag:7+EfCpr1MFnB89b9zcpvHQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRHlocko0VDdJVFJSdnVn
            cDRPVTR6a1l0Z2JPVW9NNERaaGtxU2ZGamprClhxVEowc254cTlja0dqMXQ2MXda
            RjI5eUFtcXZVNzJRWjlzemJjN1hlWjQKLS0tIFJ6NUhraklqa3hZeVBKSGZtMmxu
            Wm45V2lkRVBpUWYzdU1EQnExQTcwUnMKPH6QcbjtwsoNkGqGlPx6baJuhGY/F3/u
            IYn3rXBFdlf1PbfAlmC/A7nRKiQMG12uDyyIt+M91nUZ9WBXa/Rz/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:23:55Z"
    mac: ENC[AES256_GCM,data:9mYG8VuGkxYvLakPiwnjUAkkVHyUjowfeORYTn6v6LD/aY8HlG60cXk5aFIUm/G4vhVIvHolrcxkbuH2430094s5Htna5QOhEG4HZi6MZOD/Vh2Ot3GPydZIdIwkvBPGZiOSN46zi2PSapowOijMcLZC4nLFLQWD4j3tonEzQrY=,iv:Tgwgk7RfzLScPYD3sSetRORexa4EgO937HcLqtFQmmI=,tag:7DH8iE4JWxJv5qjKddRh3A==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
