---
# https://artifacthub.io/packages/helm/traefik/traefik
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: traefik
      # upgrade path: 30.1.0 -> 38.0.1 (rely on traefik-crds)
      version: 38.0.1 
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true
