grafana:
    adminPassword: ENC[AES256_GCM,data:ymTODIQuL39s+M6y,iv:1l7Mxxoew51sN69CMSi0pNLZjqktd6YhP94OZhGly4o=,tag:8o/vSIm4VSdNzqoI9qx9lQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TFlYUzRtQjBiM0R4MFVn
            NldvV2NwSENxeHZlUFR2YUNUZTdlellHRWxZCitvZmhSRVkxdW4wY2dCMVNoWkhC
            ajFSSThnVHgxejlFMmpXUWphREFkNGMKLS0tIDFRUFh6M1hCQkN6VTd1UnpsbVFC
            S1ZYNnIzRGE4eWZ5ZlIyY0lUaGc4RDgKN5D2ZEsExjbgq1xGENYitKK5nQKDnz+o
            NKeq8AqChdGE3X1bXYrSBlYquqBcGr/s8t71NLO1Zs8IQ88WAbUutg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:26Z"
    mac: ENC[AES256_GCM,data:lJ0YzXFGvsDbsDucBt96Ba5YN3iAivG7CoMW6r0uN6236cRcn85cp6EQl2gHIOPj1+4Pa8MCNhGYD6NsyXnsBn5uNxG8m4LVns7MwiWpHzz32PW4Gpzn+QTEYnNvlxl641mUQ0OCoC0G/vrDYLDPyYfdKdAUv3e4/leZH3TOIug=,iv:t1yIUaVgiNB8GigW97YVR69NGPKao2d9D4QhMzHaMs0=,tag:k2ltNuOMNJ2Tr7R3y2uf/A==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
