---
# Keep kustomization namespace empty so resources preserve ${NS} placeholders
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # - pv-manual-ftp.yaml
  # - pvc-manual-ftp.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: nextcloud-ingress
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/postBuild/substitute/HOST
        value: nextcloud.sharkbi.online
      - op: replace
        path: /spec/path
        value: ./manifests/ingress/overlays/winfra-test