---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-ftp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: 140.113.24.81
    path: /volume1/FTP
