---
# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  uninstall:
    keepHistory: false
    disableHooks: false
    deletionPropagation: foreground
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 61.7.2
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true
