apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-ingress
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/ingress/overlays/<cluster-name>
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
    namespace: flux-system
  postBuild:
    substitute:
      APP_NAME: grafana
      NS: observability
      HOST: grafana.example.com
      SVC: grafana
      PORT: '80'
  dependsOn:
    - name: traefik-manifests
    - name: cert-manager-manifests
    - name: observability-app
