apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-ingress
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/ingress/overlays/<cluster-name>
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
    namespace: flux-system
  postBuild:
    substitute:
      APP_NAME: prometheus
      NS: observability
      HOST: prometheus.example.com
      SVC: prometheus-server
      PORT: '80'
  dependsOn:
    - name: traefik-manifests
    - name: cert-manager-manifests
    - name: observability-app
