auth:
    rootPassword: ENC[AES256_GCM,data:K4BSe6sGI2Ah6FxG,iv:a7rlMtoht59NUQA/7twa98bnv8thWrf3gbb3LVe6GYo=,tag:a0wgboi3VUTE9bX2YfW2eg==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVzZ0cG5waGJ2YzNZSGZN
            Nmg1Y3p2amN5dFJNTE1PYmJoNFl0bUxHcFVJCklNd2ZkckNPbkd5OHRZWXdrdXRL
            NTlKMDJ3Ulc5V1JHUG13a2k4YlJqNjQKLS0tIGRHMDJrQmFvekxBdFl1eGNlS2ZG
            dm9HTWlGRm9JM0R2K2FKT0VOTm1VbkUKJ3/dhZFA5cr+vNqEX2N7rDkLYnRYrMgy
            Gw83w7fZ1CtMrex8n2LmfSMzztayCps0qjKipo5JW6fj2wyFR+w1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:18Z"
    mac: ENC[AES256_GCM,data:c135fBy4XhTKZFwLK1mbRapiHPrB/4ZIJnDVjnj7g1xEFQrpCuMpPA5qYpWhvyK84+HCk6O9X6ONNdWoq5lqJhlP8Oo6Y1F9GpccRY1SXTz8OJqLtkSVQ9xmOf8EUHwX+GSgxYdWGDiaq8wikY4vCWzb6iatudasjuaMrykUBGk=,iv:DsfiZzgwMijpCYnTpsSwpspt1aHy1iZklp/JkX3Wpqc=,tag:8p/MBGnOtGgXlACCmn3RPQ==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
