auth:
    adminPassword: ENC[AES256_GCM,data:zQA20qz/9x7NA9ra,iv:DP7e2A6kewVj25cQqgsg+2svEVnSarFiYOzgu6WiNOw=,tag:NjsTgg4Aeb4fh9q+v2te6w==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WGg2UExSL0xCUUsvQ2Q3
            Z3hqM1BkM29aK0l1ZGhXdWxQM2k1Q1dZb1dVCmdwQU9OQjg5SzlSRzRVTk5zRFBi
            N3ZqV1Z5emU3Uk44ZGZBcmpzcGVzUEEKLS0tIGZ3czA2ZEV6dU5EQ0l6NjNVMkZ1
            VThXT29hNUJzTDJyUmdSbkU1aDJBUUkKJXb6qNgQ53ozQUjGqURtp/6urOb6nipi
            i0LwwwQ9JjoNyMu6SFJarNgNTtIWf0EA/tSmSOBcpHUE+azmh2/2TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:13Z"
    mac: ENC[AES256_GCM,data:m5a7LNTuOJzzahV4WRhOsiMjNlEgSvBwcYPAwbSa4dWvb2y60a1kxAFx8upolnCTefY1jJCcjj171Pq6qVPTWl8ITASoAoREZ02jWQxddmoq8/QwquXZfvvXBVM2oridQalWaMF8Cw+E7JTl0UF4G0MJSmDL8OLyVOS7AuS69T8=,iv:dCBBcAy55I2ijeqQOwsWLQR6cp5eHOWl2mK7YHZyUX0=,tag:aKoQiy4Kz9e6qRBE82ob8w==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
