postgresql:
    postgresqlPassword: ENC[AES256_GCM,data:V8DBNiCEZcA/OHzp,iv:qfXDespnykjYLqX/O0JXgPjxJYuR0XgH59Q1XQoEjzM=,tag:lpiIaIOANnMBGtSzDdfCFQ==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYXhHSTNZc3g3M0l5YkM4
            bkdmejZMQnp3UEs4blpWZE9jL1A4eEZKTUZVCkZtNEN3cWJLbVd2Um16UFJJZ3Bp
            eFg3SUgzZ09abCtJMk8xMDUydDZ6UzQKLS0tIFFHTUFISWhmNEtVWElNNnpHbGVq
            ckNnMkp3SmU3eldyT21JNHVpcFlUN1UKbgCsZtOJeHry2fS4Jvrr+Q82EaDXY+nS
            +VqmG7zoGt2yIPUNrnn+0Xmz/Xk0Z34ebTXC2iprnVpet9dKW8fIsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:27Z"
    mac: ENC[AES256_GCM,data:vkRovg+hyvmaDlibWK7QpFktgpcLE/ieiqXxVFe9qQc7VJ8jGaV6enziWCHcByVoCZe8iNP7ZzuvmL38pyLfk4o6HbXvfyaBSRBZADzRa818w4NBWxuutl+mnMXqwLCMwtLhmPU0DKCSsqM54d45XJkhSOs6II87zivnN2zxjqs=,iv:YDb+gCMG3aMsQOuIL1MRQsnaFOQfH1sV21J/Vcg04dk=,tag:R42X7Uw3KeIZzFQ6yDtcCA==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
