---
clusterName: winfra-prod
talosVersion: v1.11.4
kubernetesVersion: v1.33.6
endpoint: https://192.168.101.201:6443
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
machine:
  network:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
  time:
    servers:
      - time.cloudflare.com
      - time.google.com
nodes:
  - hostname: kmaster1
    ipAddress: 192.168.101.71
    controlPlane: true
    installDisk: /dev/sda
  - hostname: kmaster2
    ipAddress: 192.168.101.72
    controlPlane: true
    installDisk: /dev/sda
  - hostname: kmaster3
    ipAddress: 192.168.101.73
    controlPlane: true
    installDisk: /dev/sda
  - hostname: kworker1
    ipAddress: 192.168.101.74
    controlPlane: false
    installDisk: /dev/sda
  - hostname: kworker2
    ipAddress: 192.168.101.75
    controlPlane: false
    installDisk: /dev/sda
  - hostname: kworker3
    ipAddress: 192.168.101.76
    controlPlane: false
    installDisk: /dev/sda
    