credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:S50MZV/rIfboQTD+BrwhavaWxgVXQOmlJleeVd4wt6pj/qsxdDashJ3R0MHs4alKFatLZx4mRhZazWIg9yAZbOCnWLhSBDi9i6QvR18VIw6wYdiCrCJHD2fOSI965UItMW3tdN6mVvaw62eDPnea0EgaZoE=,iv:88+D2veAwYN2oPtkYuOMa8cRbxwAXs6bfd9AVhktk2o=,tag:nremqlugiOsjvZ0QfED65A==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDZUeTZ6ekhhQmNVYW5j
            NnMxaEwraThIRThGd3hTUHhjd00zdjZ0dkNRCmJRam5zaHU0SldBdnNyVTF1SkNj
            Mm9KU3ZsbE05TFVyWlN2OVorOG9ETkUKLS0tIEQzanM1S1JkNVZzTmJiYWdYeElJ
            TmdscFhidzRnRHNEcDlUbU1lNUR4ZTAKlG+pP8lQ2z6NoqCzCxNRofpGUZtZNz4w
            pi/32GrzAZlGOfF1NH3aHSMsa/gHVdscewZfgnZvygnOh0boQvCLqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:37:28Z"
    mac: ENC[AES256_GCM,data:WaIqmN6qcytuc9L8zPrw1/SFWKVxeESLo16wPzlUUrYdpO20SEf/e9LCTW/0I8nCkE/JNM5kBQBwPnEWLbuweMVpoaO9CxCvQFudqTH9mOSbdAhN+MgiaD5/AxfS2CgWX0FQrqdBMW4zAk9nhyLoXtHzIO+D0aHegi0nWlxF+EY=,iv:hd6Sf17ZF/A3bTB9m+SApzBGsemVuMn6WtLrrHgg9ks=,tag:pSQr78ZyP/yGoFc5yiw9QQ==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
