harborAdminPassword: ENC[AES256_GCM,data:PLrtSvXvrx5KEpyR,iv:EfaonHk/aqTmUFf0B+aa9Xzgv1ginj/x91cf7VhmTiY=,tag:kMiU5mgnLSYzM3QjIRh4Pw==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMUNEdUhEakYwMnJqUDNx
            bUJHY2VXQXlZTThuQjA1Sm1XZnY2VzJGdEhFCmV3Wm9qeFlFNFR6VGh3NHFLUmpT
            anhHdk1tc1VSSWFtLysyUnlhTzJFZ28KLS0tIFQwQ2NCNEFFZnhDc0JhSisyMDVy
            TEVQVXV0NjdoT3hKUGdPN0MwTUx5TkEKUH6H5nx0XUBS1wY5IQQE/CMCYN1rd/Vp
            oEwuRlS3HPviUwnZwODYIqXD847df3BacmXoPpRfgyV5vPgQ8AfY0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:24:09Z"
    mac: ENC[AES256_GCM,data:0VQeQHMVapKfRFYZzA2IwrnPhLh5SV4Mm243bJNO7LH7Zv9Jy/FJvEKuTg2oqsaGzAdFkKF8R9bHOveyP5LQVViI4mBRR4lCYk+m2n6dJnfoa+2GXEQdBTa3/IX21acnUkcsVD1RQ45ZibuRLOZcY773vxfyGx10r+8OZ4MNJMI=,iv:BRNil6v3S4Lm6/ps4HDzSkBCaCBDQ6KY/hhwzZ83PT8=,tag:UARCm1zvghJY/PpEM8qDVA==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
