apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-ingress
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/ingress/overlays/<cluster-name>
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  postBuild:
    substitute:
      APP_NAME: gitlab
      NS: gitlab
      HOST: gitlab.example.com
      SVC: gitlab-webservice-default
      PORT: '8181'
  dependsOn:
    - name: traefik-manifests
    - name: cert-manager-manifests
    - name: gitlab-app
