---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-issuer
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # For Staging Certificate
    server: https://acme-v02.api.letsencrypt.org/directory # For Production Certificate
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
