---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: traefik
spec:
  dnsNames:
    # This will be overridden by overlays
    - example.com
  issuerRef:
    kind: ClusterIssuer
    name: ingress-issuer
  secretName: ingress-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
