nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      # treat `HelmRelease.spec.valuesFrom.name` as "name reference"
      - kind: HelmRelease
        group: helm.toolkit.fluxcd.io
        path: spec/valuesFrom/name
  - kind: Secret
    version: v1
    fieldSpecs:
      # treat `HelmRelease.spec.valuesFrom.name` as "name reference"
      - kind: HelmRelease
        group: helm.toolkit.fluxcd.io
        path: spec/valuesFrom/name

