nextcloud:
    password: ENC[AES256_GCM,data:p8WRtYcuK1c5OCsK,iv:EfLRHctR/4XAFjBtgcGhn1Nxe0tIYWxSVdzov6say3Q=,tag:fQ9TXIOPh74ccO9ExJdFwQ==,type:str]
mariadb:
    auth:
        password: ENC[AES256_GCM,data:0SQscTy6f5Owv/uj,iv:odfm62tZ8JqeDAlxSbFeo6YnR71Lc4Wku79nhRz7PjA=,tag:4WNXIalviWrcUNidmNkWiA==,type:str]
        rootPassword: ENC[AES256_GCM,data:QC6x94S2EvQjPkfN,iv:G8pz3wns+yyX/cyZXVgs6nYxkelm1RwoCfAw8Ag+mAM=,tag:x6+Xg97iReAryASpo5tkIA==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1NQbjRtM2ZpaW9JVUdp
            WHdkOGFac2hkM3duK1VhVmZsZUU1RUYvUXdrCkxaQTlmempLRklrUlo3WnJPc0N5
            WVJOMFBEWXdQWEtHbzgwNEJjRGhrTGsKLS0tIDBRTUxRZ0tubzRSajlSVXFITWl1
            bXY5Vnpoclh2MUtEb0REWFhGa0pUZTgKhXvOzkHNcOVxix1tdD7Q2WAKnBOWDFW5
            yExekyfwhMPf66PNNZvNoxPH9sM8yIygJ3QpK7JPDoA0FK89E2hkdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:24Z"
    mac: ENC[AES256_GCM,data:afKQjHyrvtJ1cLDHtZ71KBgim+pAfeiQC1FDnsBa+M5uc5pnZe3PeobsBA+sfaR5SUaYSPXkYkrc0nJQ1cEJxlJHnwkBZFfNGqg3sietH+9KakDuOfdlTN7o5n/FNt2Nuih42y/vkDqL2PNs4I3oP4Msa3cklDGffhi7BCRo09c=,iv:1brBNGRQc7YoQVirLS3wy1rDWGbBFOszTdFD6mWUICU=,tag:txWfCXK7/Z9hOySEYundvA==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|access_key_id|secret_access_key|accessKeyId|secretAccessKey|access_key|secret_key)$
    version: 3.11.0
