---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/harbor/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
  dependsOn:
    - name: harbor-app
