---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/nextcloud/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
  dependsOn:
    - name: nextcloud-app
