---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-manifests
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/gitlab/overlays/winfra-test
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
  dependsOn:
    - name: gitlab-app
