apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-ingress
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/ingress/overlays/<cluster-name>
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  postBuild:
    substitute:
      APP_NAME: nextcloud
      NS: nextcloud
      HOST: nextcloud.example.com
      SVC: nextcloud
      PORT: '8080'
  dependsOn:
    - name: traefik-manifests
    - name: cert-manager-manifests
    - name: nextcloud-app
