# This manifest creates the keycloak-oidc secret for GitLab OIDC authentication
# The secret data should be created manually or via sealed-secrets
# kubectl create secret generic -n gitlab keycloak-oidc --from-file=provider=provider.yaml
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-oidc
stringData:
    provider: ENC[AES256_GCM,data:xqG0UuNkTNg1quMtRxoOWj77RLPpAkHoAxIBOMyfrUP4CadLGrRYtPJYip0miV3FR0gbmcUVswP0+RbKUWuQHHP7G97XfoVa4wq8nx6KE+QUSgbp1qczJIoz0ID48MYMSNlX2p2rHDWP29kZt9cKlDhHjRkbloCyPEUtiMhRSZLdkMhDQpiKoAXY4SK4Yei5QrPzUrTvi6kTvKcK/khasw0JBLuVpYLQBAXchHrvjqY/6YzgGmBjpluKCphK6J0UYIgdTbjD2/71BZWbC+9HGYvn3i3BUOcmntzUXRqfrXrviG01qXAqSTUnzfU4gs23ZdCRip7aJ/pzFM/CltEVhWlR5oUwycz6ZtDOTYa4cSYcGF+84RbKBFhFeJpn6d4/Ok7p9w/95Mlrsal1G5pzpZ6+V9ezzdsJLBrvda/M7SvW9Zs5wcapqFbcYFn+1ovEoign9GXQnxMHU/spnRqL1IeeQBBQXTso01uKvmZPb3khAqSXUGt/AvfdtSxDxBLJcM2DHVWiAyGBiLHku72LZSpZy2nH/6aPsTTV2u+iHDpi8+vYDq3zKJ3NCX24rOTjEJwHNO89ndFOFWd2fy4MVxYTGKbczs9CgErDAXks8qeu8+wWngZR0bgJ,iv:dOVlPIQIUFU9H5/yYHlzRmKrbyevEt3IrxD02oIXLuo=,tag:DAYOkKf5JGMiUzFdPvoJ2w==,type:str]
sops:
    age:
        - recipient: age1czjw3cf6t4633av2dca9r845fp3wvjz333m5fqw74h0ryrrnn5xqjnyuug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNWpQMW4rRlkyY1BoSTBB
            anovSkw2R1dIVkdqVmlpYy9CSnRwQ1lSeEVVCkRtMkQ4elk0L0RVUWdXNzlwMVZF
            NWw3WDFrWWpJaFg3WGtVOGx0WG9vNDgKLS0tIEd2UWdra2RjZUVaOFNjTFQ2cGlW
            Y20rT0VkUzNqcFBFV3pUYzZnY3E4MWcKigiFrgeNf3vfLDGNELG33yuNDQKhPIng
            69GV6LWavaue6dFcUMDaMjdO9TewZhk54pBqpHlhp5/Z58INBBTU4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T12:43:37Z"
    mac: ENC[AES256_GCM,data:ZU60PCU3ib0xWP6TCVnmNIKxiP8/CxaGVEyICEcj78HRdOgB3Z8LCZWU4niJxvgj8Uyk2fCNEoZ9BRuOGLoYTi/W12jLItt+9HbO4VbnctO869p4tnbs3zCmnzwISVtb3X7I2nWeGXA+zWFogoRPJXpsb0vKcIDu8igvvAzmMvE=,iv:HNbzvOI5Z/DrJUrmkqv6m2dw2DOXaIfaly+hFE+z6RY=,tag:jsazVHqzdPsT+RMopBLYlw==,type:str]
    encrypted_regex: ^(password|secret|key|token|credential|adminPassword|harborAdminPassword|rootPassword|postgresqlPassword|secretContents|secrets\.yml|provider)$
    version: 3.11.0
